// Categorías semánticas para los chips de meta (habitaciones aparte).
// Cada kind se mapea a un único icono en components/humano-web/MetaIcon.tsx,
// de modo que un mismo concepto use siempre el mismo icono en todo el site
// y que items del mismo "universo" (p.ej. Gimnasio o Salas) no repitan icono.
export type MetaKind =
  | "time"
  | "floor"
  | "breakfast"
  | "food"
  | "grill"
  | "drinks"
  | "reception"
  | "concierge"
  | "seating"
  | "guidance"
  | "work"
  | "connectivity"
  | "wifi"
  | "machines"
  | "routine"
  | "pool"
  | "meeting"
  | "equipped"
  | "transport"
  | "airport"
  | "vehicle"
  | "pet"
  | "weight"
  | "price"
  | "laundry"
  | "wash"
  | "room"
  | "cleaning"
  | "parking"
  | "feature"
