import type { LucideIcon } from "lucide-react"
import {
  Activity,
  Armchair,
  BedDouble,
  Briefcase,
  Building2,
  CarFront,
  Clock3,
  Coffee,
  Compass,
  ConciergeBell,
  Dog,
  Dumbbell,
  Flame,
  Martini,
  ParkingCircle,
  Plane,
  Presentation,
  Scale,
  Shirt,
  Signal,
  Sparkles,
  Tag,
  Truck,
  Users,
  UtensilsCrossed,
  WashingMachine,
  Waves,
  Wifi,
} from "lucide-react"

import type { MetaKind } from "@/lib/humano/metaKinds"

const META_ICONS: Record<MetaKind, LucideIcon> = {
  time: Clock3,
  floor: Building2,
  breakfast: Coffee,
  food: UtensilsCrossed,
  grill: Flame,
  drinks: Martini,
  reception: ConciergeBell,
  concierge: ConciergeBell,
  seating: Armchair,
  guidance: Compass,
  work: Briefcase,
  connectivity: Signal,
  wifi: Wifi,
  machines: Dumbbell,
  routine: Activity,
  pool: Waves,
  meeting: Users,
  equipped: Presentation,
  transport: CarFront,
  airport: Plane,
  vehicle: Truck,
  pet: Dog,
  weight: Scale,
  price: Tag,
  laundry: Shirt,
  wash: WashingMachine,
  room: BedDouble,
  cleaning: Sparkles,
  parking: ParkingCircle,
  feature: Sparkles,
}

export function getMetaIcon(kind: MetaKind): LucideIcon {
  return META_ICONS[kind] ?? Sparkles
}
